### ISSUE TITLE
Possible to integrate this with Cell? It works fine in ElvUI for example but on the Cell frames nothing show up.

### ISSUE THREAD

**Issue by Larsy93** [dev7355608/ClassicHealPrediction#10]
Possible to integrate this with the addon Cell? It works fine in ElvUI for example but on the Cell frames nothing show up.

**Comment by dev7355608** [comment]
ClassicHealPrediction adds healing predication only to the Blizzard frames. ElvUI has its own healing predication implementation, you don't need ClassicHealPrediction for that. Cell would have to implement healing prediction themselves as well.

**Comment by Larsy93** [comment]
This is not correct. Your addon adds HoTs to the ElvUI frames as well, their healing prediction does not include HoTs but when downloading/enabling yours it shows up on theirs aswell. I am 100% sure of this.

**Comment by dev7355608** [comment]
I did not not this was the case. I suppose ElvUI reskins the Blizzard frames somehow instead of creating their own frames like Cell, which I expected ElvUI to do as well. The interaction of ClassicHealPredicition with ElvUI is entirely unintentional.

**Comment by Larsy93** [comment]
Okay, thanks for reply.
