### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by cryptoretard25** [dev7355608/ClassicHealPrediction#4]
Not working on latest WOTLK version

**Comment by dev7355608** [comment]
If there is one, what does the error message say?

**Comment by cryptoretard25** [comment]
Hey! no error messages at all, friendly heals doesnt appears at standart raid frames, its all. It works great for me in Ulduar and early ToC, but then something happens. btw addon competitor "healsbarsclassic" works fine

**Comment by dev7355608** [comment]
I think this was fixed and I forgot to close this issue.
