### ISSUE TITLE
[Season of Discovery] LUA error when using Lifebloom

### ISSUE THREAD

**Issue by Epsynus** [dev7355608/ClassicHealPrediction#5]
When using Lifebloom on the Season of Discovery realms it throws the following LUA error.

8x ...lPrediction/libs/LibHealComm-4.0-110/LibHealComm-4.0.lua:819: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@ClassicHealPrediction/libs/LibHealComm-4.0-110/LibHealComm-4.0.lua"]:819: in function <...lPrediction/libs/LibHealComm-4.0/LibHealComm-4.0.lua:808>
[string "@ClassicHealPrediction/libs/LibHealComm-4.0-110/LibHealComm-4.0.lua"]:968: in function <...lPrediction/libs/LibHealComm-4.0/LibHealComm-4.0.lua:966>
[string "@ClassicHealPrediction/libs/LibHealComm-4.0-110/LibHealComm-4.0.lua"]:2720: in function `?'
[string "@ClassicHealPrediction/libs/LibHealComm-4.0-110/LibHealComm-4.0.lua"]:3374: in function <...lPrediction/libs/LibHealComm-4.0/LibHealComm-4.0.lua:3372>

Locals:
spellData = <table> {
 levels = <table> {
 }
 bomb = <table> {
 }
 coeff = 0.520000
 interval = 1
 ticks = 7
 averages = <table> {
 }
 dhCoeff = 0.343350
}
spellName = "Lifebloom"
spellID = 408124
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 12
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 12

In case it helps here is the tooltip for Lifebloom at lvl 13.
[https://imgur.com/a/49YLA02](https://imgur.com/a/49YLA02)

**Comment by Epsynus** [comment]
Can find an updated LibHealComm-4.0 here that solves the issue.
[https://github.com/raethkcj/LibHealComm-4.0](https://github.com/raethkcj/LibHealComm-4.0)

**Comment by jicksaw** [comment]
Here's other LibHealComm forks:
Used by a maintained fork of LunaUI: https://github.com/caboyd/LibHealComm-4.0
Used by VuhDo: https://github.com/Ivaria/LibHealComm-4.0

**Comment by dev7355608** [comment]
Thanks for letting me know about the forks! I switched to https://github.com/Ivaria/LibHealComm-4.0, which seems to be the most up to date.
